version: '3'

services:
  mongo:
    container_name: sports-db
    image: mongo:6.0.13
    volumes:
      - ./database/mongo:/data/sports
    ports:
      - 27017:27017
    restart: always
  
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./database/mariadb:/data/users
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example